import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  bg: {
    flex: 1,
    backgroundColor: "#f8fafd",
    paddingTop: 40,
  },
  header: {
    padding: 24,
    borderBottomLeftRadius: 32,
    borderBottomRightRadius: 32,
    alignItems: "center",
    marginBottom: 10,
    elevation: 4,
    flexDirection: "row",
    justifyContent: "space-between",
  },
  title: {
    color: "#fff",
    fontSize: 28,
    fontWeight: "bold",
    letterSpacing: 1,
  },
  configBtn: {
    backgroundColor: "#3ba4e6",
    borderRadius: 16,
    padding: 8,
    elevation: 2,
  },
  avatarArea: {
    alignItems: "center",
    marginTop: 10,
    marginBottom: 18,
  },
  avatar: {
    width: 110,
    height: 110,
    borderRadius: 55,
    borderWidth: 4,
    borderColor: "#6EBBEB",
    backgroundColor: "#e3f2fd",
  },
  editAvatar: {
    position: "absolute",
    bottom: 0,
    right: 110 / 2 - 22,
    backgroundColor: "#3ba4e6",
    borderRadius: 18,
    padding: 6,
    elevation: 2,
  },
  infoCard: {
    backgroundColor: "#fff",
    borderRadius: 18,
    marginHorizontal: 24,
    padding: 18,
    elevation: 3,
    marginBottom: 18,
  },
  infoRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 12,
  },
  infoLabel: {
    fontSize: 15,
    color: "#3ba4e6",
    fontWeight: "bold",
    marginLeft: 8,
    marginRight: 4,
  },
  infoText: {
    fontSize: 15,
    color: "#3E6A85",
    fontWeight: "bold",
    marginLeft: 2,
  },
  editBtn: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#3ba4e6",
    borderRadius: 14,
    paddingVertical: 10,
    paddingHorizontal: 24,
    alignSelf: "center",
    elevation: 2,
    marginTop: 10,
  },
  editBtnText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "bold",
    marginLeft: 8,
    letterSpacing: 0.5,
  },
  sectionCard: {
    backgroundColor: "#fff",
    borderRadius: 18,
    marginHorizontal: 24,
    padding: 16,
    elevation: 2,
    marginBottom: 18,
  },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 8,
  },
  sectionTitle: {
    fontSize: 16,
    color: "#3ba4e6",
    fontWeight: "bold",
    marginLeft: 8,
  },
  switchRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 6,
    marginBottom: 2,
  },
  switchLabel: {
    fontSize: 15,
    color: "#3E6A85",
    fontWeight: "bold",
  },
  memberRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 10,
    backgroundColor: "#e3f2fd",
    borderRadius: 10,
    padding: 8,
  },
  memberName: {
    fontSize: 15,
    color: "#3E6A85",
    fontWeight: "bold",
  },
  memberType: {
    fontSize: 13,
    color: "#3ba4e6",
  },
  logoutBtn: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#f44336",
    borderRadius: 14,
    paddingVertical: 10,
    paddingHorizontal: 24,
    alignSelf: "center",
    elevation: 2,
    marginTop: 10,
    marginBottom: 30,
  },
  logoutText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "bold",
    marginLeft: 8,
    letterSpacing: 0.5,
  },
  modalBg: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.25)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalCard: {
    backgroundColor: "#fff",
    borderRadius: 18,
    padding: 24,
    width: "85%",
    elevation: 6,
  },
  modalTitle: {
    fontSize: 20,
    color: "#3ba4e6",
    fontWeight: "bold",
    marginBottom: 18,
    textAlign: "center",
  },
  modalInput: {
    fontSize: 15,
    color: "#222",
    backgroundColor: "#e3f2fd",
    borderRadius: 8,
    paddingVertical: 8,
    paddingHorizontal: 12,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: "#90caf9",
  },
  modalBtns: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 10,
  },
  saveBtn: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#3ba4e6",
    borderRadius: 10,
    paddingVertical: 8,
    paddingHorizontal: 18,
    elevation: 2,
  },
  cancelBtn: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#f44336",
    borderRadius: 10,
    paddingVertical: 8,
    paddingHorizontal: 18,
    elevation: 2,
  },
  saveBtnText: {
    color: "#fff",
    fontSize: 15,
    fontWeight: "bold",
    marginLeft: 6,
  },
   tabBar: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "#e3f2fd",
    flexDirection: "row",
    justifyContent: "space-around",
    height: 60,
    height: 60,
    borderTopWidth: 1,
    borderTopColor: "#cfd8dc",
    paddingBottom: 4,
  },
  tabItem: {
    alignItems: "center",
    justifyContent: "center",
    flex: 1,
  },
  tabText: {
    fontSize: 11,
    color: "#3ba4e6",
    marginTop: 2,
    fontWeight: "bold",
  },
  backBtn: {
  position: "absolute",
  left: 15,
  top: 15,
  zIndex: 10,
},
});

export default styles;